In [146]:
import pandas as pd
import numpy as np

In [147]:
nameofcol = ['AgencyNumber','AgencyName','CardholderLastName','CardholderFirstInitial','Description','Amount','Vendor','TransactionDate','PostedDate','MerchantCategoryCode(MCC)']

In [110]:
df2010 = pd.read_csv('PCard_Data FY2010.csv', encoding='utf-8',names = nameofcol, skiprows =1,dtype=str)
df2011 = pd.read_csv('PCard_Data FY2011.csv', encoding='utf-8',names = nameofcol, skiprows =1,dtype=str)
df2012 = pd.read_csv('PCard_Data FY2012.csv', encoding='utf-8',names = nameofcol, skiprows =1,dtype=str)
df2013 = pd.read_csv('PCard_Data FY2013.csv', encoding='utf-8',names = nameofcol, skiprows =1,dtype=str)
df2014 = pd.read_csv('PCard_Data FY2014.csv', encoding='utf-8',names = nameofcol, skiprows =1,dtype=str)
df2015 = pd.read_csv('PCard_Data FY2015.csv', encoding='utf-8',names = nameofcol, skiprows =1,dtype=str)
df2015.sample(5)

,AgencyNumber,AgencyName,CardholderLastName,CardholderFirstInitial,Description,Amount,Vendor,TransactionDate,PostedDate,MerchantCategoryCode(MCC)
339824,34000,OKLAHOMA STATE DEPARTMENT OF HEALTH,Cannady,C,ROOM CHARGES,$650.88,GAYLORD TEXAN FRONT DESK,NaN,NaN,GAYLORD OPRYLAND
229569,34500,DEPARTMENT OF TRANSPORTATION,Paul,S,GENERAL PURCHASE,$31.98,PAYPAL TOMMYDEAL,NaN,NaN,ELECTRONICS STORES
362531,92200,OKLAHOMA HOUSING FINANCE AGENCY,Schweitzer,D,GENERAL PURCHASE,$318.08,THE MEADOWS,NaN,NaN,SPECIAL TRADE CONTRACTORS
158879,34600,OKLA. SPACE INDUSTRY DEV. AUTH.,Vowell,K,GENERAL PURCHASE,$166.80,ELK CITY DAILY NEWS INC,10/6/2014 0:00,10/7/2014 0:00,NEWS DEALERS AND NEWSSTANDS
117680,1000,OKLAHOMA STATE UNIVERSITY,Shakya,K,POLYTETRAFLUOROETHYLENE EA,$354.14,SIGMA ALDRICH US,9/30/2014 0:00,10/1/2014 0:00,DIRCT MARKETING/DIRCT MARKETERS--NOT ELSEWHERE...

In [111]:
combined = pd.concat([df2010,df2011,df2012,df2013,df2014,df2015])
combined.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2281562 entries, 0 to 437578
Data columns (total 10 columns):
AgencyNumber                 object
AgencyName                   object
CardholderLastName           object
CardholderFirstInitial       object
Description                  object
Amount                       object
Vendor                       object
TransactionDate              object
PostedDate                   object
MerchantCategoryCode(MCC)    object
dtypes: object(10)
memory usage: 191.5+ MB

In [135]:
combined['Amount']= combined['Amount'].str.replace('$','')
combined['Amount']= combined['Amount'].str.replace('(', '-')
combined['Amount']= combined['Amount'].str.replace(')', '')
combined['Amount']= combined['Amount'].str.replace(',', '')
combined['Amount']= combined['Amount'].str.strip()
combined.CardholderLastName = combined.CardholderLastName.str.upper()

In [113]:
combined['Description']=combined['Description'].str.strip()
combined['Vendor']=combined['Vendor'].str.strip()
combined['MerchantCategoryCode(MCC)']=combined['MerchantCategoryCode(MCC)'].str.strip()

In [114]:
combined.TransactionDate = combined.TransactionDate.str.replace('00:00:00','')
combined.TransactionDate = combined.TransactionDate.str.replace('0:00','')
combined.sample(8)

,AgencyNumber,AgencyName,CardholderLastName,CardholderFirstInitial,Description,Amount,Vendor,TransactionDate,PostedDate,MerchantCategoryCode(MCC)
211452,76000,UNIVERSITY OF OKLAHOMA,BOATNER,G,2X2-8 CEDAR EA|2X2-8 CEDAR EA|CLAW HAMMER EA|1...,63.97,THE HOME DEPOT 3906,1-Dec-11,5-Dec-11,HOME SUPPLY WAREHOUSE STORES
82106,76000,UNIVERSITY OF OKLAHOMA,BOATNER,G,Transaction Line Item,17.95,WALGREENS #6477 000006477,6-Aug-10,9-Aug-10,Drug Stores Pharmacies
214604,76000,UNIVERSITY OF OKLAHOMA,REYNOLDS,C,PAD LGL RL RCY 5X8 WE,14.71,STAPLES BROOMFIELD CO,16-Feb-11,18-Feb-11,Stationary Office Supplies Printing and Writing
119347,40000,OFFICE OF JUVENILE AFFAIRS,ROWLAND,C,REFILL-TAPE MAGIC 3/4 X 12 RL|DUST DESTROYER 7...,142.11,STAPLES,7/10/2013,7/11/2013 0:00,"STATIONERY, OFFICE SUPPLIES, PRINTING AND WRIT..."
409035,1000,OKLAHOMA STATE UNIVERSITY,MUNDAY,T,GENERAL PURCHASE,830.73,REXEL2442,7-Jun-12,8-Jun-12,ELECTRICAL PARTS AND EQUIPMENT
154311,34000,OKLAHOMA STATE DEPARTMENT OF HEALTH,DAVIS,B,AIR TRAVEL,25.00,AGENT FEE 8900640433603,11/4/2014,11/6/2014 0:00,AIRLINES AND AIR CARRIERS
208742,80000,OKLA. CAREER AND TECHNOLOGY EDUCATION,GOODNER,M,GENERAL PURCHASE,1788.13,SHI CORP,11/15/2014,11/17/2014 0:00,"COMPUTERS, COMPUTER PERIPHERAL EQUIPMENT, SOFT..."
41648,34500,DEPARTMENT OF TRANSPORTATION,WICKWARE,F,GENERAL TRANSACTION,387.31,CLAMPITT PAPER OKLAHOM,18-Aug-10,19-Aug-10,

In [115]:
combined.PostedDate = combined.PostedDate.str.replace('00:00:00','')
combined.PostedDate = combined.PostedDate.str.replace('0:00','')

In [116]:
combined = combined.dropna(subset=['TransactionDate','PostedDate']).copy()

In [117]:
dfdash = combined[combined.TransactionDate.str.contains(pat=r'^\d{1,2}-')].copy()
dfdash = combined[combined.PostedDate.str.contains(pat=r'^\d{1,2}-')].copy()
dfdot = combined[combined.TransactionDate.str.contains(pat=r'^\d{1,2}\.')].copy()
dfdot = combined[combined.PostedDate.str.contains(pat=r'^\d{1,2}\.')].copy()
dfslash = combined[combined.TransactionDate.str.contains(pat=r'^\d{1,2}/')].copy()
dfslash = combined[combined.PostedDate.str.contains(pat=r'^\d{1,2}/')].copy()
dfdash.TransactionDate = pd.to_datetime(dfdash.TransactionDate, format='%d-%b-%y') 
dfdash.PostedDate = pd.to_datetime(dfdash.PostedDate, format='%d-%b-%y') 
dfdot.TransactionDate = dfdot.TransactionDate.str.strip()
dfdot.TransactionDate = pd.to_datetime(dfdot.TransactionDate, format='%d.%m.%Y') 
dfdot.PostedDate = dfdot.PostedDate.str.strip()
dfdot.PostedDate = pd.to_datetime(dfdot.PostedDate, format='%d.%m.%Y') 
dfslash.TransactionDate = dfslash.TransactionDate.str.strip()
dfslash.TransactionDate = pd.to_datetime(dfslash.TransactionDate, format='%m/%d/%Y')
dfslash.PostedDate = dfslash.PostedDate.str.strip()
dfslash.PostedDate = pd.to_datetime(dfslash.PostedDate, format='%m/%d/%Y')

In [118]:
dfNew = pd.concat([dfdash,dfdot,dfslash])
dfOSU=dfNew[dfNew['AgencyName'] == 'OKLAHOMA STATE UNIVERSITY']
dfOSU.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 489178 entries, 0 to 139239
Data columns (total 10 columns):
AgencyNumber                 489178 non-null object
AgencyName                   489178 non-null object
CardholderLastName           489178 non-null object
CardholderFirstInitial       489178 non-null object
Description                  489069 non-null object
Amount                       489178 non-null object
Vendor                       489178 non-null object
TransactionDate              489178 non-null datetime64[ns]
PostedDate                   489178 non-null datetime64[ns]
MerchantCategoryCode(MCC)    489178 non-null object
dtypes: datetime64[ns](2), object(8)
memory usage: 41.1+ MB

In [119]:
#analysis 1

In [120]:
ana1=dfOSU[(dfOSU['TransactionDate'].dt.month==1)&(dfOSU['TransactionDate'].dt.year==2014)].sort_values('Amount',ascending=False)[0:3]
ana1.append(dfOSU[(dfOSU['TransactionDate'].dt.month==2)&(dfOSU['TransactionDate'].dt.year==2014)].sort_values('Amount',ascending=False)[0:3])
ana1.append(dfOSU[(dfOSU['TransactionDate'].dt.month==3)&(dfOSU['TransactionDate'].dt.year==2014)].sort_values('Amount',ascending=False)[0:3])
ana1.append(dfOSU[(dfOSU['TransactionDate'].dt.month==4)&(dfOSU['TransactionDate'].dt.year==2014)].sort_values('Amount',ascending=False)[0:3])
ana1.append(dfOSU[(dfOSU['TransactionDate'].dt.month==5)&(dfOSU['TransactionDate'].dt.year==2014)].sort_values('Amount',ascending=False)[0:3])
ana1.append(dfOSU[(dfOSU['TransactionDate'].dt.month==6)&(dfOSU['TransactionDate'].dt.year==2014)].sort_values('Amount',ascending=False)[0:3])
ana1.append(dfOSU[(dfOSU['TransactionDate'].dt.month==7)&(dfOSU['TransactionDate'].dt.year==2014)].sort_values('Amount',ascending=False)[0:3])
ana1.append(dfOSU[(dfOSU['TransactionDate'].dt.month==8)&(dfOSU['TransactionDate'].dt.year==2014)].sort_values('Amount',ascending=False)[0:3])
ana1.append(dfOSU[(dfOSU['TransactionDate'].dt.month==9)&(dfOSU['TransactionDate'].dt.year==2014)].sort_values('Amount',ascending=False)[0:3])
ana1.append(dfOSU[(dfOSU['TransactionDate'].dt.month==10)&(dfOSU['TransactionDate'].dt.year==2014)].sort_values('Amount',ascending=False)[0:3])
ana1.append(dfOSU[(dfOSU['TransactionDate'].dt.month==11)&(dfOSU['TransactionDate'].dt.year==2014)].sort_values('Amount',ascending=False)[0:3])
ana1.append(dfOSU[(dfOSU['TransactionDate'].dt.month==12)&(dfOSU['TransactionDate'].dt.year==2014)].sort_values('Amount',ascending=False)[0:3])

,AgencyNumber,AgencyName,CardholderLastName,CardholderFirstInitial,Description,Amount,Vendor,TransactionDate,PostedDate,MerchantCategoryCode(MCC)
62050,1000,OKLAHOMA STATE UNIVERSITY,CARTER,A,GENERAL PURCHASE,998.9,ALLEGRA PRINT AND IMAGING,2014-01-15,2014-01-16,"DURABLE GOODS, NOT ELSEWHERE CLASSIFIED"
61644,1000,OKLAHOMA STATE UNIVERSITY,BELLARD,E,GENERAL PURCHASE,996.3,BROWN AVIATION TOOL,2014-01-15,2014-01-15,HARDWARE STORES
57095,1000,OKLAHOMA STATE UNIVERSITY,MOREY,A,GENERAL PURCHASE,996.2,ALLEGRA PRINT AND IMAGING,2014-01-02,2014-01-03,"DURABLE GOODS, NOT ELSEWHERE CLASSIFIED"
137306,1000,OKLAHOMA STATE UNIVERSITY,LEWIS,W,5-BAY 5BIG NAS PRO - UP TO Ea,999.00,"B&H PHOTO, 800-606-6969",2014-12-22,2014-12-23,DIRCT MARKETING/DIRCT MARKETERS--NOT ELSEWHERE...
132942,1000,OKLAHOMA STATE UNIVERSITY,LOWERY,A,Audience Response System EA,995.31,TURNING TECHNOLOGIES,2014-12-12,2014-12-15,"COMPUTERS, COMPUTER PERIPHERAL EQUIPMENT, SOFT..."
135309,1000,OKLAHOMA STATE UNIVERSITY,TORNAKIAN,M,GENERAL PURCHASE,992.95,OKLAHOMA CITY WINNELSO,2014-12-04,2014-12-05,PLUMBING AND HEATING EQUIPMENT AND SUPPLIES

In [121]:
#analysis 2

In [142]:
dfOSU['CardholderID'] = dfOSU['CardholderFirstInitial'].str.cat(dfOSU['CardholderLastName'],sep=' ')
dfOSU2014=dfOSU[(dfOSU['TransactionDate'] >= '2014-01-01') & (dfOSU['TransactionDate'] <= '2014-12-31')]
Analysis_2 = pd.pivot_table(data=dfOSU2014,index='CardholderID',values='Amount',aggfunc='count')
Analysis_2.sort_values(by='Amount', ascending = False).head(5)

/Users/diyang/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

              Amount
CardholderID
G HINES         3510
J HEUSEL        2435
R BOWERS        2392
M TORNAKIAN     2008
T MUNDAY        1102

In [123]:
#analysis 3

In [124]:
dfOSU['Year'] =  dfOSU['TransactionDate'].dt.year
dfOSU2014 = dfOSU[dfOSU['Year']==2014]
dfOSU2014.head()

/Users/diyang/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,AgencyNumber,AgencyName,CardholderLastName,CardholderFirstInitial,Description,Amount,Vendor,TransactionDate,PostedDate,MerchantCategoryCode(MCC),CardholderID,Year
56333,1000,OKLAHOMA STATE UNIVERSITY,REDDINGTON,D,GENERAL PURCHASE,735,ABSA,2014-01-03,2014-01-06,SCHOOLS AND EDUCATIONAL SERVICES NOT ELSEWHERE...,D REDDINGTON,2014
56334,1000,OKLAHOMA STATE UNIVERSITY,REECE,S,GENERAL PURCHASE,304.04,ORSCHELN DURANT 83,2014-01-03,2014-01-06,HARDWARE STORES,S REECE,2014
56335,1000,OKLAHOMA STATE UNIVERSITY,REECE,S,GENERAL PURCHASE,39.19,ORSCHELN DURANT 83,2014-01-03,2014-01-06,HARDWARE STORES,S REECE,2014
56336,1000,OKLAHOMA STATE UNIVERSITY,RENDINA,E,GENERAL PURCHASE,260,CELLSIGNAL.COM,2014-01-02,2014-01-06,"DRUGS, DRUG PROPRIETARIES, AND DRUGGISTS SUNDRIES",E RENDINA,2014
56337,1000,OKLAHOMA STATE UNIVERSITY,REX,T,GENERAL PURCHASE,80,THERMACUBE 00 OF 00,2014-01-02,2014-01-06,BUSINESS SERVICES NOT ELSEWHERE CLASSIFIED,T REX,2014

In [128]:
dfOSU2014['Amount'] = dfOSU2014['Amount'].astype(float)
x = dfOSU2014[['MerchantCategoryCode(MCC)','Amount']].groupby('MerchantCategoryCode(MCC)')
result = x.sum().sort_values('Amount',ascending=False).head(10)
result

/Users/diyang/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

                                                        Amount
MerchantCategoryCode(MCC)
DENTAL/LABORATORY/MEDICAL/OPHTHALMIC HOSP EQIP ...  2475758.68
INDUSTRIAL SUPPLIES NOT ELSEWHERE CLASSIFIED        1451575.70
BUSINESS SERVICES NOT ELSEWHERE CLASSIFIED          1446174.85
MISCELLANEOUS AND SPECIALTY RETAIL STORES           1406160.44
COMMERCIAL EQUIPMENT, NOT ELSEWHERE CLASSIFIED      1265726.79
BOOK STORES                                          873288.87
DIRCT MARKETING/DIRCT MARKETERS--NOT ELSEWHERE ...   850553.27
ELECTRICAL PARTS AND EQUIPMENT                       782225.41
STATIONERY, OFFICE SUPPLIES, PRINTING AND WRITI...   765950.74
PLUMBING AND HEATING EQUIPMENT AND SUPPLIES          716419.67

In [129]:
#Internal Control Test 1

In [130]:
dfOSU2014['Name']=dfOSU2014['CardholderLastName']+'-'+dfOSU2014['CardholderFirstInitial']
dfOSU2014['TransactionMonth']=dfOSU2014['TransactionDate'].dt.month
ICTest1 = pd.pivot_table(data=dfOSU2014,
              index=['Name','TransactionMonth'],
              values='Amount',
              aggfunc= np.sum)
ICT1= ICTest1[ICTest1.Amount > 10000].sort_values('Amount',ascending=False)
ICT1

/Users/diyang/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/Users/diyang/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

                                        Amount
Name               TransactionMonth
HINES-G            6                 176844.86
                   5                 164111.86
                   3                 153774.22
                   1                 149700.14
                   4                 147219.43
                   8                 146289.90
                   10                140436.29
                   7                 137953.20
TORNAKIAN-M        4                 134802.33
HINES-G            9                 129820.10
TORNAKIAN-M        3                 113441.46
                   1                 112598.39
                   2                 110591.38
HEUSEL-J           1                 110190.56
HINES-G            2                 109682.82
TORNAKIAN-M        9                 109472.43
HEUSEL-J           6                 106698.70
TORNAKIAN-M        11                100626.01
HEUSEL-J           5                  99099.45
                   4                  96795.87
TORNAKIAN-M        7                  95919.46
HEUSEL-J           2                  95862.41
TORNAKIAN-M        10                 93010.89
MUNDAY-T           8                  91423.91
TORNAKIAN-M        5                  80555.52
                   6                  80015.17
                   8                  79539.79
MUNDAY-T           9                  79156.45
FORQUER-H          12                 79012.41
HEUSEL-J           3                  77203.22
...                                        ...
SPEARS-J           2                  10325.92
TURNER-D           6                  10321.72
CLAWSON-S          1                  10282.54
MONTELONGO-M       3                  10259.87
GORDON-D           4                  10255.45
KELOUGH-N          12                 10253.47
BOYD-K             3                  10251.72
BALLARD-J          12                 10244.69
BUSER-M            6                  10227.81
SUNDSTROM-K        12                 10221.92
LOWERY-A           4                  10219.60
GUETZ-B            5                  10181.72
TEEL-J             2                  10181.04
GEBHART-G          9                  10176.03
FITZPATRICK-S      8                  10161.91
WEST-B             8                  10151.84
BRINKER-B          7                  10146.82
EHRLICH-K          6                  10138.27
BUDD-C             9                  10133.19
HOLBA-D            9                  10119.24
MOREY-A            3                  10089.78
SANTHANAKRISHNAN-A 4                  10057.65
BURNS-R            6                  10046.59
HODGES-N           9                  10023.59
BIGGS-J            2                  10019.78
STINE-J            4                  10018.32
TAYLOR-R           11                 10015.15
HUNTER-D           7                  10013.81
ROBINSON-S         6                  10004.97
HUANG-C            9                  10004.23

[458 rows x 1 columns]

In [144]:
#Internal Control Test 2

In [145]:
dfict2=dfOSU[dfOSU['TransactionDate'].dt.year==2014]
dfict2['Amount']=dfict2['Amount'].astype(float)
pvt=pd.pivot_table(data=dfict2,
               index=['CardholderLastName','CardholderFirstInitial','Vendor','TransactionDate'],
               values='Amount',
               aggfunc=['count','sum'])
internal2= pvt[(pvt[('sum','Amount')]>5000) & (pvt[('count','Amount')]>1)].sort_values('TransactionDate')
internal2

/Users/diyang/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

                                                                                     count  \
                                                                                    Amount
CardholderLastName CardholderFirstInitial Vendor                    TransactionDate
TORNAKIAN          M                      R.B. AKINS COMPANY        2014-01-06           4
                                          AUTOMATED BUILDNG SYSTEMS 2014-01-08           3
HINES              G                      OKLAHOMA CONTRACTORS SUP  2014-01-16           3
HEUSEL             J                      ANIXTER-115687            2014-01-23           2
KENNEDY            J                      COUNCIL OF GRADUATE SCHO  2014-02-04           2
KINDSCHI           J                      VETERANS AFFRS DMC        2014-02-12           3
HINES              G                      OKLAHOMA CONTRACTORS SUP  2014-02-20           3
KINDSCHI           J                      VETERANS AFFRS DMC        2014-02-24          11
                                                                    2014-03-06           8
HINES              G                      GRIGSBY'S CARPET SHOWROOM 2014-03-10           3
BAKER              B                      AMBASSADOR HOTEL OKLAH    2014-03-23           7
DAVIS              E                      HILTON HOTELS ADV RESV    2014-03-29           9
TORNAKIAN          M                      FERGUSON ENTERPRISES #88  2014-03-31           2
HINES              G                      FEDERAL COPRORATION       2014-04-04           2
HEUSEL             J                      ANIXTER-115687            2014-04-08           3
HINES              G                      BRENNTAG SOUTHWEST        2014-04-15           5
TORNAKIAN          M                      AUTOMATED BUILDNG SYSTEMS 2014-04-22           3
STOVER             C                      COCKRELL EYECARE CENTER   2014-04-24           2
TORNAKIAN          M                      OKLAHOMA CITY WINNELSO    2014-04-24           4
HINES              G                      ECONOMY SUPPLY INC        2014-04-24           5
TORNAKIAN          M                      FEDERAL COPRORATION       2014-04-30           2
HINES              G                      ECONOMY SUPPLY INC        2014-05-07           3
LENOIR             K                      BIO TEK INSTRUMENTS       2014-05-15           2
HINES              G                      OKLAHOMA CONTRACTORS SUP  2014-05-15           2
                                          MURRY WOMBLE INC          2014-05-16           2
MOREY              A                      ALLEGRA PRINT AND IMAGING 2014-05-19           4
HINES              G                      KOONS GAS MEASUREMENT     2014-05-19           3
SINGH              R                      DOUBLETREE HOTEL BETHESDA 2014-05-22          11
CLARK              C                      POLARIS MEDICAL ACADEMY   2014-06-10           2
COWELL             C                      JAILHOUSE FEED  FARM      2014-06-30           2
...                                                                                    ...
HINES              G                      A PLUS AUTO GLASS         2014-07-25           6
                                          ECONOMY SUPPLY INC        2014-07-29           6
TORNAKIAN          M                      UNITED REFRIG BR #89      2014-07-29           2
GOTCHER            M                      TURF TEAM                 2014-08-06           3
HINES              G                      INTERMOUNTAIN LOCK AND SE 2014-08-11           3
                                          BRENNTAG SOUTHWEST        2014-08-22           4
CLARK              M                      Amazon Payments           2014-08-27           2
MUNDAY             T                      INTERMOUNTAIN LOCK AND SE 2014-08-29           2
SANTHANAKRISHNAN   A                      Amazon.com                2014-09-08           4
HINES              G                      BRENNTAG SOUTHWEST        2014-09-09           6
BAILEY             J                      WWW.N-OADN.ORG            2014-09-11           8
HEATON             D                      SCANTRON CORPORATION      2014-09-12           2
HINES              G                      ECONOMY SUPPLY INC        2014-09-17           2
WILLIAMS           J                      HILTON BOSTON DOWNTOWN    2014-09-24           2
HINES              G                      REXEL2442                 2014-10-10           5
BRINKER            B                      LOWES #00241              2014-10-10           2
COOPER             E                      BIOMED DIAGNOSTICS INC    2014-10-14           2
KINDSCHI           J                      VETERANS AFFRS DMC        2014-10-15           6
                                                                    2014-10-17           7
WICK               J                      OK DEPT OF CAREER TECH    2014-10-21           3
HINES              G                      BRENNTAG SOUTHWEST        2014-10-22           2
KINDSCHI           J                      VETERANS AFFRS DMC        2014-10-23           5
FORQUER            H                      BRENNTAG SOUTHWEST        2014-10-30           5
TORNAKIAN          M                      MECHANICAL SALES KC       2014-11-07           2
                                          SIMPLEX GRINNELL WEB P    2014-11-13           8
                                          OKLAHOMA CITY WINNELSO    2014-12-04           2
WOOD               C                      MEDLEY MATERIAL HANDLING  2014-12-12           2
WILKINSON          T                      PHONAK HEARING SYS        2014-12-17           6
KINDSCHI           J                      VETERANS AFFRS DMC        2014-12-22           2
EDWARDS            W                      IN  MAVERICK JACKETS INC  2014-12-24           2

                                                                                          sum
                                                                                       Amount
CardholderLastName CardholderFirstInitial Vendor                    TransactionDate
TORNAKIAN          M                      R.B. AKINS COMPANY        2014-01-06        5164.00
                                          AUTOMATED BUILDNG SYSTEMS 2014-01-08        6063.30
HINES              G                      OKLAHOMA CONTRACTORS SUP  2014-01-16        5130.00
HEUSEL             J                      ANIXTER-115687            2014-01-23        5775.10
KENNEDY            J                      COUNCIL OF GRADUATE SCHO  2014-02-04        5166.00
KINDSCHI           J                      VETERANS AFFRS DMC        2014-02-12        6821.03
HINES              G                      OKLAHOMA CONTRACTORS SUP  2014-02-20        5041.00
KINDSCHI           J                      VETERANS AFFRS DMC        2014-02-24        7490.94
                                                                    2014-03-06        8631.55
HINES              G                      GRIGSBY'S CARPET SHOWROOM 2014-03-10        8319.67
BAKER              B                      AMBASSADOR HOTEL OKLAH    2014-03-23        5115.88
DAVIS              E                      HILTON HOTELS ADV RESV    2014-03-29        9019.17
TORNAKIAN          M                      FERGUSON ENTERPRISES #88  2014-03-31        6338.41
HINES              G                      FEDERAL COPRORATION       2014-04-04        5341.80
HEUSEL             J                      ANIXTER-115687            2014-04-08        5442.62
HINES              G                      BRENNTAG SOUTHWEST        2014-04-15        8128.84
TORNAKIAN          M                      AUTOMATED BUILDNG SYSTEMS 2014-04-22        5024.14
STOVER             C                      COCKRELL EYECARE CENTER   2014-04-24        6503.97
TORNAKIAN          M                      OKLAHOMA CITY WINNELSO    2014-04-24        6339.93
HINES              G                      ECONOMY SUPPLY INC        2014-04-24       10017.68
TORNAKIAN          M                      FEDERAL COPRORATION       2014-04-30        5082.53
HINES              G                      ECONOMY SUPPLY INC        2014-05-07        6478.76
LENOIR             K                      BIO TEK INSTRUMENTS       2014-05-15        5027.44
HINES              G                      OKLAHOMA CONTRACTORS SUP  2014-05-15        5676.00
                                          MURRY WOMBLE INC          2014-05-16        5166.00
MOREY              A                      ALLEGRA PRINT AND IMAGING 2014-05-19        5980.82
HINES              G                      KOONS GAS MEASUREMENT     2014-05-19       11483.49
SINGH              R                      DOUBLETREE HOTEL BETHESDA 2014-05-22       21020.26
CLARK              C                      POLARIS MEDICAL ACADEMY   2014-06-10        5800.00
COWELL             C                      JAILHOUSE FEED  FARM      2014-06-30        5015.70
...                                                                                       ...
HINES              G                      A PLUS AUTO GLASS         2014-07-25        5273.55
                                          ECONOMY SUPPLY INC        2014-07-29        9455.48
TORNAKIAN          M                      UNITED REFRIG BR #89      2014-07-29        5003.71
GOTCHER            M                      TURF TEAM                 2014-08-06        6675.00
HINES              G                      INTERMOUNTAIN LOCK AND SE 2014-08-11        7670.50
                                          BRENNTAG SOUTHWEST        2014-08-22        8698.18
CLARK              M                      Amazon Payments           2014-08-27        6000.00
MUNDAY             T                      INTERMOUNTAIN LOCK AND SE 2014-08-29        8610.00
SANTHANAKRISHNAN   A                      Amazon.com                2014-09-08        5235.42
HINES              G                      BRENNTAG SOUTHWEST        2014-09-09        5113.65
BAILEY             J                      WWW.N-OADN.ORG            2014-09-11        5210.00
HEATON             D                      SCANTRON CORPORATION      2014-09-12        6560.20
HINES              G                      ECONOMY SUPPLY INC        2014-09-17        6810.00
WILLIAMS           J                      HILTON BOSTON DOWNTOWN    2014-09-24       15326.88
HINES              G                      REXEL2442                 2014-10-10        5496.28
BRINKER            B                      LOWES #00241              2014-10-10        6996.64
COOPER             E                      BIOMED DIAGNOSTICS INC    2014-10-14        9186.87
KINDSCHI           J                      VETERANS AFFRS DMC        2014-10-15       10937.06
                                                                    2014-10-17       12976.96
WICK               J                      OK DEPT OF CAREER TECH    2014-10-21        6840.00
HINES              G                      BRENNTAG SOUTHWEST        2014-10-22        5604.91
KINDSCHI           J                      VETERANS AFFRS DMC        2014-10-23       12658.72
FORQUER            H                      BRENNTAG SOUTHWEST        2014-10-30        6411.91
TORNAKIAN          M                      MECHANICAL SALES KC       2014-11-07        7332.52
                                          SIMPLEX GRINNELL WEB P    2014-11-13        6227.00
                                          OKLAHOMA CITY WINNELSO    2014-12-04        5966.80
WOOD               C                      MEDLEY MATERIAL HANDLING  2014-12-12        5296.32
WILKINSON          T                      PHONAK HEARING SYS        2014-12-17        6214.60
KINDSCHI           J                      VETERANS AFFRS DMC        2014-12-22        6582.50
EDWARDS            W                      IN  MAVERICK JACKETS INC  2014-12-24        5398.35

[66 rows x 2 columns]

In [ ]:
#fraud test 1

In [ ]:
def count_first_digit(data_str):
    mask=dfOSU2014[data_str]>=1
    data=list(dfOSU2014[mask][data_str]) 
    for i in range(len(data)):
        data[i] =str(data[i])
        data[i]=data[i][0]
    first_digits=[int(x) for x in data]
    unique=(set(first_digits))#a list with unique values of first_digit list
    data_count=[]
    for i in unique:
        count=first_digits.count(i)
        data_count.append(count)
    total_count=sum(data_count)
    data_percentage=[(i/total_count)*100 for i in data_count]
    for i in range(len(data_percentage)):
        data_percentage[i] = round(data_percentage[i],1)
    Fraud_test_1 = pd.DataFrame({'Digits':[1,2,3,4,5,6,7,8,9],'Percentage':data_percentage})
    return  Fraud_test_1
   
count_first_digit('Amount')

In [ ]:
#fraud test 2 duplicate transaction

In [ ]:
dfOSU2014['UniqueName']= dfOSU2014['CardholderLastName'] + dfOSU2014['CardholderFirstInitial']
dfOSU2014.sample(5)

In [ ]:
FT2 = dfOSU2014[dfOSU2014['Amount'] > 0]
F2 = FT2.groupby(by=['TransactionDate','Vendor','UniqueName','Amount']).agg({'Amount':'count'})
F2.columns = ['Count']
F2 = F2[F2.Count>1]
F2

In [ ]:
#Fraud Test 2: Worst Offenders

In [150]:
df_WF = F2.sort_values(['Count'], ascending = False)
df_WF.head(10)

                                                            Count
TransactionDate Vendor                   UniqueName Amount
2014-04-11      AMAZON MKTPLACE PMTS     GORDOND    16.03      35
2014-02-24      WYNDHAM GARDEN HOTEL     HASELEYS   89.00      33
2014-11-09      LA QUINTA INN & SUITES   ROASEAUK   166.00     20
                FAIRFIELD INN-STILLWATER BISHOPK    83.00      20
2014-01-13      IBT IIS FINGERPRINT COM  CLARKK     53.00      18
2014-04-30      PROMETRIC    EXAM FEE    LONGANS    24.95      17
2014-04-13      HOLIDAY INNS             ROASEAUK   166.00     16
2014-08-19      DOMINO'S 6460            SIMMONSS   5.00       15
2014-02-23      HAMPTON INNS FT WORTH    SANDERSOND 90.85      15
2014-09-24      QUALITY INN              ROBINSOND  160.00     15

In [156]:
# Addtional Test 
#No more than 5 days between transaction date and posted date to ensure bookkeeping is in a timely manner.

In [152]:
dfOSU2014['diff_days'] = (dfOSU2014.PostedDate - dfOSU2014.TransactionDate).dt.days

/Users/diyang/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [153]:
dfOSU2014['diff_days'] = (dfOSU2014.PostedDate - dfOSU2014.TransactionDate).dt.days
dfOSU2014.head()

/Users/diyang/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,AgencyNumber,AgencyName,CardholderLastName,CardholderFirstInitial,Description,Amount,Vendor,TransactionDate,PostedDate,MerchantCategoryCode(MCC),CardholderID,Year,diff_days
56333,1000,OKLAHOMA STATE UNIVERSITY,REDDINGTON,D,GENERAL PURCHASE,735,ABSA,2014-01-03,2014-01-06,SCHOOLS AND EDUCATIONAL SERVICES NOT ELSEWHERE...,D REDDINGTON,2014,3
56334,1000,OKLAHOMA STATE UNIVERSITY,REECE,S,GENERAL PURCHASE,304.04,ORSCHELN DURANT 83,2014-01-03,2014-01-06,HARDWARE STORES,S REECE,2014,3
56335,1000,OKLAHOMA STATE UNIVERSITY,REECE,S,GENERAL PURCHASE,39.19,ORSCHELN DURANT 83,2014-01-03,2014-01-06,HARDWARE STORES,S REECE,2014,3
56336,1000,OKLAHOMA STATE UNIVERSITY,RENDINA,E,GENERAL PURCHASE,260,CELLSIGNAL.COM,2014-01-02,2014-01-06,"DRUGS, DRUG PROPRIETARIES, AND DRUGGISTS SUNDRIES",E RENDINA,2014,4
56337,1000,OKLAHOMA STATE UNIVERSITY,REX,T,GENERAL PURCHASE,80,THERMACUBE 00 OF 00,2014-01-02,2014-01-06,BUSINESS SERVICES NOT ELSEWHERE CLASSIFIED,T REX,2014,4

In [154]:
dfOSU2014[dfOSU2014.diff_days>5]

,AgencyNumber,AgencyName,CardholderLastName,CardholderFirstInitial,Description,Amount,Vendor,TransactionDate,PostedDate,MerchantCategoryCode(MCC),CardholderID,Year,diff_days
58744,1000,OKLAHOMA STATE UNIVERSITY,JONES,L,GENERAL PURCHASE,69,RAD SYSTEMS,2014-01-23,2014-01-29,SCHOOLS AND EDUCATIONAL SERVICES NOT ELSEWHERE...,L JONES,2014,6
58953,1000,OKLAHOMA STATE UNIVERSITY,MASON,C,GENERAL PURCHASE,-35.46,HAMPTON INN & SUITES LAWT,2014-01-22,2014-01-28,HAMPTON INNS,C MASON,2014,6
59831,1000,OKLAHOMA STATE UNIVERSITY,HOOD,K,GENERAL PURCHASE,3350.31,A.M.M.R. SERVICES INC,2014-01-16,2014-01-27,HARDWARE STORES,K HOOD,2014,11
60097,1000,OKLAHOMA STATE UNIVERSITY,TORNAKIAN,M,GENERAL PURCHASE,9.75,SOUTHERN MATERIAL HANDLIN,2014-01-23,2014-01-30,"COMMERCIAL EQUIPMENT, NOT ELSEWHERE CLASSIFIED",M TORNAKIAN,2014,7
60135,1000,OKLAHOMA STATE UNIVERSITY,HARRIMAN,T,GENERAL PURCHASE,424.42,BRUKER NANO INC,2014-01-09,2014-01-31,DENTAL/LABORATORY/MEDICAL/OPHTHALMIC HOSP EQIP...,T HARRIMAN,2014,22
60761,1000,OKLAHOMA STATE UNIVERSITY,HINES,G,GENERAL PURCHASE,180.75,STILLWATER WINNELSON C,2014-01-09,2014-01-30,PLUMBING AND HEATING EQUIPMENT AND SUPPLIES,G HINES,2014,21
61083,1000,OKLAHOMA STATE UNIVERSITY,TORNAKIAN,M,GENERAL PURCHASE,658.21,STILLWATER WINNELSON C,2014-01-15,2014-01-27,PLUMBING AND HEATING EQUIPMENT AND SUPPLIES,M TORNAKIAN,2014,12
61130,1000,OKLAHOMA STATE UNIVERSITY,WILSON,J,Indoor Sensor Cover Colo EA,-214.04,WW GRAINGER,2014-01-22,2014-01-28,INDUSTRIAL SUPPLIES NOT ELSEWHERE CLASSIFIED,J WILSON,2014,6
61245,1000,OKLAHOMA STATE UNIVERSITY,TORNAKIAN,M,Argon Hose40V82R-33 Ft. EA,-26.06,WW GRAINGER,2014-01-21,2014-01-28,INDUSTRIAL SUPPLIES NOT ELSEWHERE CLASSIFIED,M TORNAKIAN,2014,7
61705,1000,OKLAHOMA STATE UNIVERSITY,LEDFORD,P,LAB SVCS EA,150.07,QDI DIAG LAB OKLAHOMA,2014-01-09,2014-01-17,MEDICAL AND DENTAL LABORATORIES,P LEDFORD,2014,8
61706,1000,OKLAHOMA STATE UNIVERSITY,LEDFORD,P,LAB SVCS EA,150.07,QDI DIAG LAB OKLAHOMA,2014-01-09,2014-01-17,MEDICAL AND DENTAL LABORATORIES,P LEDFORD,2014,8
61707,1000,OKLAHOMA STATE UNIVERSITY,LEDFORD,P,LAB SVCS EA,150.07,QDI DIAG LAB OKLAHOMA,2014-01-09,2014-01-17,MEDICAL AND DENTAL LABORATORIES,P LEDFORD,2014,8
61708,1000,OKLAHOMA STATE UNIVERSITY,LEDFORD,P,LAB SVCS EA,150.07,QDI DIAG LAB OKLAHOMA,2014-01-09,2014-01-17,MEDICAL AND DENTAL LABORATORIES,P LEDFORD,2014,8
61763,1000,OKLAHOMA STATE UNIVERSITY,CHESSMORE,G,GENERAL PURCHASE,22.47,SKYPE COMMUNICATIO,2014-01-07,2014-01-13,CONTINUITY/SUBSCRIPTION MERCHANTS,G CHESSMORE,2014,6
61965,1000,OKLAHOMA STATE UNIVERSITY,FANNING,B,GENERAL PURCHASE,18.27,RED ROCK BAKERY AND DELI,2014-01-09,2014-01-16,EATING PLACES AND RESTAURANTS,B FANNING,2014,7
62203,1000,OKLAHOMA STATE UNIVERSITY,BAKER,L,GENERAL PURCHASE,30.9,SAGE PUBLICATIONS INC.,2014-01-07,2014-01-13,"BOOKS, PERIODICALS AND NEWSPAPERS",L BAKER,2014,6
62445,1000,OKLAHOMA STATE UNIVERSITY,SISSON,M,GENERAL PURCHASE,346.63,DANIEL SMITH INC,2014-01-06,2014-01-13,ARTIST SUPPLY AND CRAFT STORES,M SISSON,2014,7
62490,1000,OKLAHOMA STATE UNIVERSITY,ANDERSON,M,GENERAL PURCHASE,376.61,Abnova(Taiwan)Corporation,2014-01-09,2014-01-16,MEDICAL SERVICES & HEALTH PRACTITIONERS NOT EL...,M ANDERSON,2014,7
62631,1000,OKLAHOMA STATE UNIVERSITY,MUTSCHELKNAUS,S,GENERAL PURCHASE,9.99,SKYPE,2014-01-06,2014-01-13,TELECOMMUNICATION SERVICES,S MUTSCHELKNAUS,2014,7
62712,1000,OKLAHOMA STATE UNIVERSITY,PETERS,B,EA,-676.99,LC INDUSTRIES INC,2014-01-06,2014-01-13,"STATIONERY, OFFICE SUPPLIES, PRINTING AND WRIT...",B PETERS,2014,7
63057,1000,OKLAHOMA STATE UNIVERSITY,NICHOLS,L,GENERAL PURCHASE,-3.95,IVY GARTH SEEDS AND PLANT,2014-01-07,2014-01-14,"FLORISTS SUPPLIES, NURSERY STOCK & FLOWERS",L NICHOLS,2014,7
63884,1000,OKLAHOMA STATE UNIVERSITY,ROBINSON,S,GENERAL PURCHASE,236,EMD CHEMICALS,2014-01-17,2014-01-23,CHEMICALS AND ALLIED PRODUCTS NOT ELSEWHERE CL...,S ROBINSON,2014,6
63948,1000,OKLAHOMA STATE UNIVERSITY,DAVIS,M,GENERAL PURCHASE,160.92,HOLIDAY INN EXPRESS CASPR,2014-01-15,2014-01-21,HOLIDAY INNS,M DAVIS,2014,6
63952,1000,OKLAHOMA STATE UNIVERSITY,DAVIS,M,GENERAL PURCHASE,-200,CLAIM ADJ/CHEVRON 0035646,2014-01-04,2014-01-21,AUTOMATED FUEL DISPENSER,M DAVIS,2014,17
63953,1000,OKLAHOMA STATE UNIVERSITY,DAVIS,M,GENERAL PURCHASE,-200,CLAIM ADJ/CHEVRON 0030686,2014-01-06,2014-01-21,AUTOMATED FUEL DISPENSER,M DAVIS,2014,15
64043,1000,OKLAHOMA STATE UNIVERSITY,BARTLETT,L,GENERAL PURCHASE,-1930.16,SOURCEONE HEALTHCARE,2014-01-07,2014-01-20,DENTAL/LABORATORY/MEDICAL/OPHTHALMIC HOSP EQIP...,L BARTLETT,2014,13
64122,1000,OKLAHOMA STATE UNIVERSITY,MARGWARTH,P,15 WATT - CLEAR - A15 EA,489,1000BULBS.COM,2014-01-16,2014-01-23,HARDWARE STORES,P MARGWARTH,2014,7
64182,1000,OKLAHOMA STATE UNIVERSITY,HOLBA,D,GENERAL PURCHASE,294,PENSKE MISTER MUFFLER BR,2014-01-16,2014-01-23,TRUCK AND UTILITY TRAILER RENTALS,D HOLBA,2014,7
64257,1000,OKLAHOMA STATE UNIVERSITY,SHAKYA,K,AIR TRAVEL,368.5,UNITED 0167325158541,2014-01-13,2014-01-20,UNITED AIRLINES,K SHAKYA,2014,7
64422,1000,OKLAHOMA STATE UNIVERSITY,YARBROUGH-TESSMAN,V,GENERAL PURCHASE,-219,MILA INTERNATIONAL INC,2014-01-15,2014-01-22,DENTAL/LABORATORY/MEDICAL/OPHTHALMIC HOSP EQIP...,V YARBROUGH-TESSMAN,2014,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
136509,1000,OKLAHOMA STATE UNIVERSITY,THACKER,G,GENERAL PURCHASE,574.50,PENSKE MISTER MUFFLER BR,2014-12-15,2014-12-22,TRUCK AND UTILITY TRAILER RENTALS,G THACKER,2014,7
136748,1000,OKLAHOMA STATE UNIVERSITY,ORCUTT,R,GENERAL PURCHASE,50.00,SHRED-IT OKLAHOMA CITY,2014-12-17,2014-12-26,BUSINESS SERVICES NOT ELSEWHERE CLASSIFIED,R ORCUTT,2014,9
136753,1000,OKLAHOMA STATE UNIVERSITY,REED,J,GENERAL PURCHASE,5000.00,AIR SYSTEM AND PUMP SOLUT,2014-12-12,2014-12-26,"COMMERCIAL EQUIPMENT, NOT ELSEWHERE CLASSIFIED",J REED,2014,14
136888,1000,OKLAHOMA STATE UNIVERSITY,ROSS,S,GENERAL PURCHASE,-1050.00,APEX SERVICES,2014-12-12,2014-12-26,EXTERMINATING AND DISINFECTING SERVICES,S ROSS,2014,14
136973,1000,OKLAHOMA STATE UNIVERSITY,TODD,R,Invoice or Order Number EA,1029.00,BELDEN,2014-12-19,2014-12-26,ELECTRICAL PARTS AND EQUIPMENT,R TODD,2014,7
137018,1000,OKLAHOMA STATE UNIVERSITY,CONNER,J,GENERAL PURCHASE,-36.65,Claim ADJ/EMIRATES 000,2014-11-20,2014-12-23,EMIRATES AIRLINES,J CONNER,2014,33
137019,1000,OKLAHOMA STATE UNIVERSITY,CONNER,J,GENERAL PURCHASE,-78.54,Claim ADJ/EMIRATES 261,2014-11-20,2014-12-23,EMIRATES AIRLINES,J CONNER,2014,33
137127,1000,OKLAHOMA STATE UNIVERSITY,FORQUER,H,Back Support Black 4XL EA,-33.21,WW GRAINGER,2014-12-17,2014-12-23,INDUSTRIAL SUPPLIES NOT ELSEWHERE CLASSIFIED,H FORQUER,2014,6
137317,1000,OKLAHOMA STATE UNIVERSITY,MANI,R,GENERAL PURCHASE,1136.83,BRUKER DALTRONICS,2014-12-10,2014-12-23,DENTAL/LABORATORY/MEDICAL/OPHTHALMIC HOSP EQIP...,R MANI,2014,13
137347,1000,OKLAHOMA STATE UNIVERSITY,TEEL,J,GENERAL PURCHASE,454.44,M BRAUN,2014-12-12,2014-12-19,ELECTRICAL PARTS AND EQUIPMENT,J TEEL,2014,7
137374,1000,OKLAHOMA STATE UNIVERSITY,WARD,J,GENERAL PURCHASE,-2570.99,CLAIM ADJ/AIR CANADA 014,2014-12-07,2014-12-19,AIR CANADA,J WARD,2014,12
137375,1000,OKLAHOMA STATE UNIVERSITY,WARD,J,GENERAL PURCHASE,-4139.96,CLAIM ADJ/AIR CANADA 014,2014-12-08,2014-12-19,AIR CANADA,J WARD,2014,11
137395,1000,OKLAHOMA STATE UNIVERSITY,STROOPE,Z,GENERAL PURCHASE,-335.00,MUSIC SALES G SCHIRMER,2014-12-16,2014-12-23,MISCELLANEOUS PUBLISHING AND PRINTING SERVICES,Z STROOPE,2014,7
137432,1000,OKLAHOMA STATE UNIVERSITY,HU,J,GENERAL PURCHASE,441.33,ASP-DAC2015,2014-12-12,2014-12-29,BUSINESS SERVICES NOT ELSEWHERE CLASSIFIED,J HU,2014,17
137456,1000,OKLAHOMA STATE UNIVERSITY,WISE,S,GENERAL PURCHASE,-2019.80,CLAIM ADJ/KROGER #704,2014-12-11,2014-12-19,"GROCERY STORES,AND SUPERMARKETS",S WISE,2014,8
137837,1000,OKLAHOMA STATE UNIVERSITY,MCADAMS,K,GENERAL PURCHASE,300.00,SAPULPA DAILY HERALD,2014-12-11,2014-12-17,NEWS DEALERS AND NEWSSTANDS,K MCADAMS,2014,6
137896,1000,OKLAHOMA STATE UNIVERSITY,FORQUER,H,94 HVY-DUTY TWIN SLOT STD EA,291.20,LOUIS AND COMPANY,2014-11-28,2014-12-22,INDUSTRIAL SUPPLIES NOT ELSEWHERE CLASSIFIED,H FORQUER,2014,24
138214,1000,OKLAHOMA STATE UNIVERSITY,SHOTWELL,D,GENERAL PURCHASE,120.25,"NASHVILLE WRAPS, LLC",2014-11-20,2014-12-02,"GIFT,CARD,NOVELTY,AND SOUVENIR STORES",D SHOTWELL,2014,12
138346,1000,OKLAHOMA STATE UNIVERSITY,CARTER,S,GENERAL PURCHASE,241.78,PROVIMI NORTH AMER,2014-11-25,2014-12-01,NON-DURABLE GOODS NOT ELSEWHERE CLASSIFIED,S CARTER,2014,6
138455,1000,OKLAHOMA STATE UNIVERSITY,LOFFI CH,R,GENERAL PURCHASE,-49.40,HYATT PLACE NW,2014-11-23,2014-12-04,HYATT HOTELS/INT'L,R LOFFI CH,2014,11
138456,1000,OKLAHOMA STATE UNIVERSITY,LOFFI CH,R,GENERAL PURCHASE,-49.40,HYATT PLACE NW,2014-11-23,2014-12-04,HYATT HOTELS/INT'L,R LOFFI CH,2014,11
138457,1000,OKLAHOMA STATE UNIVERSITY,LOFFI CH,R,GENERAL PURCHASE,-49.40,HYATT PLACE NW,2014-11-23,2014-12-04,HYATT HOTELS/INT'L,R LOFFI CH,2014,11
138560,1000,OKLAHOMA STATE UNIVERSITY,TORNAKIAN,M,GENERAL PURCHASE,923.04,UNIVAR USA INC,2014-11-21,2014-12-01,CHEMICALS AND ALLIED PRODUCTS NOT ELSEWHERE CL...,M TORNAKIAN,2014,10
139001,1000,OKLAHOMA STATE UNIVERSITY,ANDERSON,J,GENERAL PURCHASE,100.00,OK DEPT OF CAREER TECH,2014-11-24,2014-12-02,GOVERNMENT SERVICES--NOT ELSEWHERE CLASSIFIED,J ANDERSON,2014,8
139008,1000,OKLAHOMA STATE UNIVERSITY,BENTLEY,G,GENERAL PURCHASE,-206.30,HOTEL INDIGO,2014-11-25,2014-12-02,HOTEL INDIGO GALLERIA HOUSTON,G BENTLEY,2014,7
139199,1000,OKLAHOMA STATE UNIVERSITY,TEEL,J,GENERAL PURCHASE,-554.86,EMD CHEMICALS,2014-11-13,2014-12-03,CHEMICALS AND ALLIED PRODUCTS NOT ELSEWHERE CL...,J TEEL,2014,20
139219,1000,OKLAHOMA STATE UNIVERSITY,HEUSEL,J,Spiral Wound Metal Gasket EA|VIROCLEAR 1X5ML E...,-22.06,WW GRAINGER,2014-11-25,2014-12-02,INDUSTRIAL SUPPLIES NOT ELSEWHERE CLASSIFIED,J HEUSEL,2014,7
139220,1000,OKLAHOMA STATE UNIVERSITY,HINES,G,GENERAL PURCHASE,167.20,STILLWATER WINNELSON C,2014-11-25,2014-12-02,PLUMBING AND HEATING EQUIPMENT AND SUPPLIES,G HINES,2014,7
139221,1000,OKLAHOMA STATE UNIVERSITY,HINES,G,GENERAL PURCHASE,1.90,STILLWATER WINNELSON C,2014-11-24,2014-12-02,PLUMBING AND HEATING EQUIPMENT AND SUPPLIES,G HINES,2014,8
139222,1000,OKLAHOMA STATE UNIVERSITY,HINES,G,GENERAL PURCHASE,383.20,STILLWATER WINNELSON C,2014-11-24,2014-12-02,PLUMBING AND HEATING EQUIPMENT AND SUPPLIES,G HINES,2014,8

In [155]:
# Interpretation: There are 1162 belated transactions record in total.

In [ ]:
# Requesting addtional data:

#1. Transaction place: We will collect data and present them into Tableau Map. If there is unusual place out of the prearranged route of scholar activities, we can assume that user make purchase out of his personal use.

#2. Transaction column on response letter: We will verify several top largest purchases by checking numbers of reponse letters from top 10 vendors to see if accurarcy criteria can be met.